#!/usr/bin/env python3
"""Generate src/stratagem_names.h from the `// Name` comments in src/stratagems.h.

Each stratagem entry in strategemItemList / strategemBaseList is preceded by two comment
lines: `// <index>` then `// <Name>`. We extract those names, in order, into two C arrays
so the firmware can show a stratagem's name (the structs themselves store no name).

Run from the repo root:  python utils/gen-stratagem-names.py
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "stratagems.h"
OUT = ROOT / "src" / "stratagem_names.h"

ITEM_AMOUNT = 91
BASE_AMOUNT = 17


def extract_region(text, decl):
    """Return the substring of `text` inside the {...} of a `decl[...] = {` list."""
    start = text.index(decl)
    brace = text.index("{", start)
    depth = 0
    for i in range(brace, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return text[brace : i + 1]
    raise ValueError(f"unterminated list for {decl!r}")


def names_in(region):
    """Names are the `// <text>` line immediately following each `// <index>` line."""
    lines = region.splitlines()
    out = []
    for i, line in enumerate(lines[:-1]):
        if re.match(r"^\s*//\s*\d+\s*$", line):
            m = re.match(r"^\s*//\s*(.+?)\s*$", lines[i + 1])
            if m:
                out.append(m.group(1))
    return out


def c_escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    text = SRC.read_text(encoding="utf-8")
    items = names_in(extract_region(text, "strategemItemList[SG_ITEM_AMOUNT]"))
    bases = names_in(extract_region(text, "strategemBaseList[SG_BASE_AMOUNT]"))

    if len(items) != ITEM_AMOUNT or len(bases) != BASE_AMOUNT:
        sys.exit(
            f"count mismatch: items={len(items)} (want {ITEM_AMOUNT}), "
            f"bases={len(bases)} (want {BASE_AMOUNT})"
        )

    def block(arr, name, count):
        body = "\n".join(f'    "{c_escape(n)}",' for n in arr)
        return f"const char *const {name}[{count}] = {{\n{body}\n}};\n"

    OUT.write_text(
        "// AUTO-GENERATED by utils/gen-stratagem-names.py from stratagems.h comments.\n"
        "// Do not edit by hand; re-run the script if the stratagem lists change.\n"
        "#ifndef _STRATAGEM_NAMES_H\n#define _STRATAGEM_NAMES_H\n\n"
        + block(items, "strategemItemNames", "SG_ITEM_AMOUNT")
        + "\n"
        + block(bases, "strategemBaseNames", "SG_BASE_AMOUNT")
        + "\n#endif\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT} ({len(items)} item names, {len(bases)} base names)")


if __name__ == "__main__":
    main()
